# frozen_string_literal: true

REQUIRE_PATTERN = /^require ["'].+?["']$/
FROZEN_STRING = '# frozen_string_literal: true'
ALL_DANGER_FILE = 'all/Dangerfile'

desc 'Generate all/Dangerfile'
task 'generate_all' do
  contents = [
    <<~HEADER
      # frozen_string_literal: true

      # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
      # RUN `rake generate_all` TO REGENERATE.

    HEADER
  ]

  Dir['lib/*.rb', '*/**/Dangerfile']
    .sort
    .reject { |file| file == ALL_DANGER_FILE }
    .each do |file|
    content = File.open(file, 'r:UTF-8', &:read)

    # inline `require` statements
    content.gsub!(REQUIRE_PATTERN, '')
    content.gsub!(FROZEN_STRING, '')
    content.gsub!(/\n\n+/, '')

    contents << "# --> #{file}:\n#{content}\n"
  end

  FileUtils.mkdir_p('all')
  File.write('all/Dangerfile', "#{contents.join.strip}\n")
end
