# frozen_string_literal: true

if git.commits.any? { |commit| commit.message.split(/\n/).first.length > 50 }
  warn <<~TEXT.gsub(/\$/, '')
    On of your commit messages is too long. Please adhere to the following \
    basic structural rules for creating a meaningful commit message:

    * Keep the first line of your commit message short (not more than 50 chars). \
      Many tools such as Github and graphical git clients strip the subject after \
      50 characters, and people working on the command line are better off with \
      text which is not too wide.
    * Keep the second line empty
    * Use the rest of the commit message to describe the commit. There’s no \
      restriction on the format nor the length, so be as descriptive and \
      informative as possible.
  TEXT
end
